# -*- coding: utf-8 -*-
"""projeto-algoritmo-de-auditoria-de-dados

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vOORrhR3ahqca3NC5dZvLsMM6GUHaqwk
"""

# O Algoritmo de Auditoria de Dados

LIMITE_SEGURANCA = 100.000
vd1 = float(input("Primeira venda: "))
vd2 = float(input("Segunda venda: "))
vd3 = float(input("Terceira venda: "))
def analisar_vendas(vd1, vd2, vd3):
 global LIMITE_SEGURANCA
media = (vd1 + vd2 + vd3) / 3

print("-"*40)
print(f"Primeira venda R$: {vd1: .2f}")
print(f"Segunda venda:R$ {vd2: .2f}")
print(f"Terceira venda R$: {vd3: .2f}")
print(f"Media vendas R$: {media: .2f}")
if media > LIMITE_SEGURANCA:
 print ("SISTEMA EM QUARENTENA")


if vd1 > media * 5:
  print ("REVISÃO MANUAL NECESSÁRIA")
elif vd2 > media * 5:
  print ("REVISÃO MANUAL NECESSÁRIA")
elif vd3 > media * 5:
 print ("REVISÃO MANUAL NECESSÁRIA")
LIMITE_SEGURANCA = media
print(f"Novo limite ajustado automaticamente para: R$ {LIMITE_SEGURANCA:.2f}")
print("-"*40)