# -*- coding: utf-8 -*-
"""desenhando-emojis-com-dados

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1co3DyHcrkocNRBYyYGyqH7t_Hy6_NnUq
"""

#exercício 1:



emoji_data = {

    "nome": "Smile",

    "grade": [

        [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)],

        [(255,255,0), (0,0,0),     (255,255,0), (0,0,0),     (255,255,0)],

        [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)],

        [(255,255,0), (0,0,0),     (0,0,0),     (0,0,0),     (255,255,0)],

        [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)]

    ]

}



nova_grade = []



for chave, conteudo in emoji_data.items():

    if chave == "grade":

        for i in range(len(conteudo)):

            nova_linha = []

            for j in range(len(conteudo[i])):

                pixel_atual = conteudo[i][j]

                if pixel_atual == (255, 255, 0):

                    novo_pixel = (pixel_atual[0]//2, pixel_atual[1]//2, pixel_atual[2]//2)

                    nova_linha.append(novo_pixel)

                else:

                    nova_linha.append(pixel_atual)

            nova_grade.append(nova_linha)



emoji_data["grade"] = nova_grade

print(emoji_data["grade"])

#exercício 2:



biblioteca_musical = {

    "Toques": [

        {"Alegre": ([440, 480], [520, 560])},

        {"Triste": ([200, 150], [100, 50])}

    ]

}



for i in range(len(biblioteca_musical["Toques"])):

    item = biblioteca_musical["Toques"][i]

    for nome in item.keys():

        matriz_original = item[nome]

        transposta = ([], [])

        for j in range(2):

            transposta[0].append(matriz_original[j][0])

            transposta[1].append(matriz_original[j][1])

        item.update({nome: transposta})



print(biblioteca_musical)

#exercício 3:



galeria = {

    "Artes": [

        {"id": 101, "pixels": [(255, 0, 0), (0, 0, 0)], "tag": "temp"},

        {"id": 102, "pixels": [(0, 255, 0), (255, 255, 255)], "tag": "temp"}

    ]

}



for nome_chave in galeria.keys():

    lista_desenhos = galeria[nome_chave]

    for i in range(len(lista_desenhos)):

        desenho = lista_desenhos[i]

        for j in range(len(desenho["pixels"])):

            cor = desenho["pixels"][j]

            print(f"Cor: {cor}")

        desenho.pop("tag")



galeria["Artes"].insert(0, {"id": 100, "pixels": [], "info": "Capa"})



print(galeria)