# -*- coding: utf-8 -*-
"""engenharia-de-contexto-e-logica-fisica

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R9IztYyhPWdNSdyfVLm5e_lQjlr6GtOO
"""

### PARTE 1: O Algoritmo do Microclima Local



def analisar_microclima():

    print("--- Análise de Microclima Urbano ---")



    dados_locais = [

        ["Largo de São Mateus", 18, 97, 84],

        ["Vila Aricanduva", 18, 72, 84],

        ["Vila Carrão", 22, 75, 85]

    ]



    for local in dados_locais:

        nome = local[0]

        print(f"\nAnalisando local: {nome}")



        for indice, dado in enumerate(local):

            if indice == 1:

                print(f"-> Temperatura: {dado}°C")

            elif indice == 2:

                print(f"-> Umidade: {dado}%")

            elif indice == 3:

                print(f"-> IQA: {dado}")



        temperatura = local[1]

        umidade = local[2]

        iqa = local[3]



        match iqa:

            case _ if iqa <= 50:

                qualidade_ar = "Boa"

            case _ if iqa <= 100:

                qualidade_ar = "Moderada"

            case _ if iqa <= 150:

                qualidade_ar = "Ruim"

            case _:

                qualidade_ar = "Muito Ruim"



        print(f"-> Classificação do ar: {qualidade_ar}")



        nota = 10



        if temperatura < 18 or temperatura > 28:

            nota -= 3

        elif temperatura < 20 or temperatura > 26:

            nota -= 1



        if umidade < 40 or umidade > 80:

            nota -= 2

        elif umidade < 50 or umidade > 70:

            nota -= 1



        if iqa > 100:

            nota -= 3

        elif iqa > 50:

            nota -= 1



        if nota < 0:

            nota = 0



        print(f"-> Nota de Conforto Urbano: {nota}/10")





analisar_microclima()

### PARTE 2: Navegação e Evacuação Espacial



def simulador_evacuacao():

    print("--- Simulador de Evacuação ---")



    locais = ["Sala", "Corredor", "Sala com chave", "Portão", "Saída"]

    estados = ["inicio", "direita fechada", "tem chave", "portao trancado", "saida"]



    posicao = 0

    energia = 10

    inventario = []

    saiu = False



    while energia > 0 and not saiu:

        print(f"\nLocal: {locais[posicao]}")

        print(f"Estado: {estados[posicao]}")



        if estados[posicao] == "inicio":

            posicao += 1



        elif estados[posicao] == "direita fechada":

            print("Tentou direita: falha")

            print("Indo pela esquerda")

            posicao += 1



        elif estados[posicao] == "tem chave":

            if "chave" not in inventario:

                inventario.append("chave")

                print("Chave coletada")

            posicao += 1



        elif estados[posicao] == "portao trancado":

            if "chave" in inventario:

                print("Portão aberto com chave")

                posicao += 1

            else:

                print("Portão trancado, voltando")

                posicao -= 1



        elif estados[posicao] == "saida":

            print("Saída encontrada")

            saiu = True



        energia -= 1

        print(f"Energia: {energia}")

        print(f"Inventário: {inventario}")



    if saiu:

        print("\nEvacuação concluída")

    else:

        print("\nSem energia")





simulador_evacuacao()