# -*- coding: utf-8 -*-
"""traduzindo-logica-para-python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ilXXgYAgZry-aDs430G1F3-cmlqPk-TG
"""

#CÓDIGO 1:



def processar_vendas():

    total_compra = 0.0

    itens_comprados = 0



    print("Quantos produtos diferentes foram comprados?")

    quantidade_tipos = int(input("Quantidade de Tipos: "))



    for i in range(quantidade_tipos):

        nome_produto = str(input(f"\nNome do produto {i+1}: "))

        preco_unitario = float(input("Qual o valor unitário do produto? "))

        quantidade_prod = int(input("Quantidade do produto: "))



        if preco_unitario <= 0 or quantidade_prod <= 0:

            print("Erro: Valores inválidos para este produto!")

            subtotal = 0

        else:

            subtotal = preco_unitario * quantidade_prod

            total_compra += subtotal

            itens_comprados += quantidade_prod



    if total_compra > 500.00:

        total_final = total_compra * 0.90

        print("Desconto de 10% aplicado!")

    elif total_compra > 200.00:

        total_final = total_compra * 0.95

        print("Desconto de 5% aplicado!")

    else:

        total_final = total_compra



    print(f"Resumo: {itens_comprados} itens. Total a pagar: R$ {total_final:.2f}")



processar_vendas()

#CÓDIGO 2:



def analisar_clima():

    soma_temperaturas = 0.0

    dias_quentes = 0

    alerta_extremo = False



    for dia in range(1, 8):

        print(f"Digite a temperatura do dia {dia}:")

        temp = float(input())



        soma_temperaturas = soma_temperaturas + temp



        if temp > 35.0:

            dias_quentes = dias_quentes + 1



        if temp > 45.0 or temp < -5.0:

            alerta_extremo = True



    media = soma_temperaturas / 7



    print(f"Média semanal: {media:.2f}")

    print(f"Dias acima de 35°C: {dias_quentes}")



    if alerta_extremo == True:

        print("CUIDADO: Condições climáticas perigosas detectadas!")

    else:

        print("Clima dentro da normalidade operacional.")



analisar_clima()

#CÓDIGO 3



def sistema_notas_turma():

    print("Quantos alunos existem na turma?")

    total_alunos = int(input())



    for j in range(1, total_alunos + 1):

        print(f" Aluno {j}")

        print("Nome do aluno:")

        aluno_nome = input()



        print("Nota 1:")

        n1 = float(input())



        print("Nota 2:")

        n2 = float(input())



        media_aluno = (n1 + n2) / 2



        if media_aluno >= 7.0:

            print(f"{aluno_nome}: Aprovado com média {media_aluno:.1f}")

        elif media_aluno >= 5.0:

            print(f"{aluno_nome}: Recuperação (Média: {media_aluno:.1f})")

        else:

            print(f"{aluno_nome}: Reprovado")



sistema_notas_turma()

#CÓDIGO 4:

def simulador_poupanca():

    print("Valor inicial do investimento:")

    saldo = float(input())



    print("Taxa de juros mensal (em %):")

    taxa = float(input())



    print("Número de meses da simulação:")

    meses = int(input())



    for m in range(1, meses + 1):

        print(f"Quanto deseja depositar no mês {m}? (0 para nenhum)")

        aporte = float(input())



        saldo = saldo + aporte

        juros = saldo * (taxa / 100)

        saldo = saldo + juros



        print(f"Mês {m}: Saldo atualizado = R$ {saldo:.2f}")



        if saldo > 10000.0:

            print(f"Parabéns! Você atingiu a meta de 10k no mês {m}")



    print(f"Resultado final após {meses} meses: R$ {saldo:.2f}")



simulador_poupanca()